dist: xenial
language: node_js
node_js:
  - lts/*

branches:
  only:
    - development
    - master

install:
  - npm install
  - npm install codecov -g

script:
  - npm test -- --coverage

after_success:
  - codecov

notifications:
  email:
    recipients:
      - perttu.karna@gmail.com
    on_success: change
    on_failure: always

